### ISSUE TITLE
Using JSON string as PubSub credentials in Python

### ISSUE THREAD

**Issue by reselbob** [GoogleCloudPlatform/google-auth-library-python#225] opened 2017-11-29 07:50 UTC
Using Python, Is it possible to use just the JSON authentication credentials instead of a declaring the path to the file the contains the JSON, like so:

```python
import os
from google.cloud import pubsub
json_string = os.environ['PUBSUB_JSON']
creds = json.loads(json_string)
client = pubsub.PublisherClient(credentials=creds)
```

I can do this technique in Node, but I am having trouble figuring out how to do the JSON only initialization in Python. When I use the `service account` technique like so:

```python
import json
from google.oauth2 import service_account

json_string = os.environ['PUBSUB_JSON']
info = json.loads(json_string)
creds = service_account.Credentials.from_service_account_info(info)
client = pubsub.PublisherClient(credentials=creds)
topic_path = client.topic_path(os.getenv('GOOGLE_CLOUD_PROJECT'), 'cron_job_topic')
data = data.encode('utf-8')
future = client.publish(topic_path, data=data)
```

gives me an error:

```python
google.auth.exceptions.RefreshError: ('invalid_scope: Empty or missing scope not allowed.', '{\n "error" : "invalid_scope",\n "error_description" : "Empty or missing scope not allowed."\n}')
```

The JSON in question works fine when declared using a file path.

Thanks in advance for any help!

**Comment by dhermes** [comment] 2017-11-29 16:20
The issue is that you haven't declared the scopes needed. For Pub / Sub you'll want to also provide:

```python
scope = 'https://www.googleapis.com/auth/pubsub'
creds = service_account.Credentials.from_service_account_info(
    info, scopes=(scope,))
```

It's worth noting that if you set the `GOOGLE_APPLICATION_CREDENTIALS` environment variable to a file containing your JSON key, then you will automatically get scoped credentials via:

```python
client = pubsub.PublisherClient()
```

(i.e. no arguments).

**Comment by dhermes** [comment] 2017-11-29 17:18
I am going to pre-emptively close this since it seems resolved.

**Closed by dhermes** 2017-11-29 17:18 UTC

**Comment by reselbob** [comment] 2017-11-29 17:33
Yes, the scope declaration you provides is the fix I needed.

Please accept my most sincere thanks for sticking with me on this one.

One last thing, have you a URL that describes what scope is about?

**Comment by dhermes** [comment] 2017-11-29 17:40
- https://developers.google.com/identity/protocols/googlescopes
- https://developers.google.com/+/web/api/rest/oauth#authorization-scopes
- https://developers.google.com/gmail/api/auth/scopes
