### ISSUE TITLE
Unable to use credentials with Google Cloud Vision via service discovery

### ISSUE THREAD

**Issue by denismakogon** [GoogleCloudPlatform/google-auth-library-python#193] opened 2017-08-26 22:00 UTC
Env details:
```
google-api-python-client==1.6.2
google-auth==1.0.2
```
Error:
```
'Credentials' object has no attribute 'authorize'
```

Code snippet:
```
            from google.oauth2 import service_account
            from googleapiclient import discovery

            credentials = service_account.Credentials.from_service_account_info(
                gcloup_map)
            service = discovery.build(
                'vision', 'v1', credentials=credentials,
                discoveryServiceUrl=DISCOVERY_URL)

```

**Comment by jonparrott** [comment] 2017-08-28 16:14
Hi @denismakogon, make sure you have both `google-auth` and `google-auth-httplib2` installed. That's typically the cause of this.

I'm gonna close this for now, but feel free to comment if that doesn't solve your issue.

**Closed by jonparrott** 2017-08-28 16:14 UTC
