### ISSUE TITLE
auth.default() takes 440ms

### ISSUE THREAD

**Issue by max-sixty** [GoogleCloudPlatform/google-auth-library-python#285] opened 2018-08-24 18:29 UTC
Is this expected? It's 750ms on the first attempt, and then falls for subsequent requests. 

We're creating a Client for each request, which calls this method. Potentially that's a bad design?

```
n [6]: import google.auth as auth

In [7]: %timeit -n 1 -r 1 auth.default()

748 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [8]: %timeit -n 1 -r 1 auth.default()

444 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

Version: 1.5.1
OS: MacOS
On a fast 1.3ms ping connection

**Comment by max-sixty** [comment] 2018-08-24 18:39
Out of curiosity I `%prun` this, and it's taking all its time with a single call to reading a file:

```
       145 function calls in 0.430 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.410    0.410    0.410    0.410 {method 'read' of 'file' objects}
        1    0.011    0.011    0.011    0.011 {posix.read}
        1    0.004    0.004    0.004    0.004 {posix.fork}
        1    0.001    0.001    0.015    0.015 subprocess.py:881(_execute_child)
        8    0.001    0.000    0.001    0.000 {fcntl.fcntl}
        2    0.000    0.000    0.000    0.000 {posix.stat}
        1    0.000    0.000    0.000    0.000 {method 'read' of '_io.TextIOWrapper' objects}
        2    0.000    0.000    0.000    0.000 decoder.py:359(decode)
        1    0.000    0.000    0.001    0.001 {_io.open}
        3    0.000    0.000    0.000    0.000 locale.py:566(setlocale)
        1    0.000    0.000    0.002    0.002 _default.py:69(_load_credentials_from_file)
        1    0.000    0.000    0.016    0.016 subprocess.py:330(__init__)
        3    0.000    0.000    0.000    0.000 {_locale.setlocale}
        4    0.000    0.000    0.001    0.000 subprocess.py:842(_set_cloexec_flag)
        1    0.000    0.000    0.429    0.429 _default.py:209(default)
        3    0.000    0.000    0.421    0.140 subprocess.py:118(_eintr_retry_call)
        1    0.000    0.000    0.427    0.427 _cloud_sdk.py:100(get_project_id)
        1    0.000    0.000    0.427    0.427 subprocess.py:190(check_output)
        1    0.000    0.000    0.411    0.411 subprocess.py:448(communicate)
        2    0.000    0.000    0.000    0.000 decoder.py:370(raw_decode)
        2    0.000    0.000    0.001    0.000 subprocess.py:855(pipe_cloexec)
        1    0.000    0.000    0.429    0.429 _default.py:138(_get_gcloud_sdk_credentials)
        4    0.000    0.000    0.000    0.000 {method 'end' of '_sre.SRE_Match' objects}
        2    0.000    0.000    0.000    0.000 {posix.pipe}
        1    0.000    0.000    0.000    0.000 posixpath.py:251(expanduser)
        1    0.000    0.000    0.000    0.000 credentials.py:143(from_authorized_user_info)
        3    0.000    0.000    0.000    0.000 {posix.close}
        1    0.000    0.000    0.000    0.000 locale.py:610(getpreferredencoding)
        3    0.000    0.000    0.000    0.000 UserDict.py:35(__getitem__)
        2    0.000    0.000    0.000    0.000 posixpath.py:61(join)
        4    0.000    0.000    0.000    0.000 {method 'match' of '_sre.SRE_Pattern' objects}
        3    0.000    0.000    0.000    0.000 UserDict.py:91(get)
        1    0.000    0.000    0.001    0.001 __init__.py:258(load)
        1    0.000    0.000    0.000    0.000 _default.py:57(_warn_about_problematic_credentials)
        1    0.000    0.000    0.000    0.000 abc.py:128(__instancecheck__)
        2    0.000    0.000    0.000    0.000 __init__.py:294(loads)
        1    0.000    0.000    0.000    0.000 _cloud_sdk.py:42(get_config_path)
        1    0.000    0.000    0.000    0.000 subprocess.py:902(_close_in_parent)
        4    0.000    0.000    0.000    0.000 {isinstance}
        1    0.000    0.000    0.430    0.430 <string>:1(<module>)
        1    0.000    0.000    0.000    0.000 subprocess.py:1072(wait)
        2    0.000    0.000    0.000    0.000 {_codecs.utf_8_decode}
        1    0.000    0.000    0.000    0.000 _cloud_sdk.py:84(load_authorized_user_credentials)
        1    0.000    0.000    0.000    0.000 {posix.fdopen}
        1    0.000    0.000    0.001    0.001 subprocess.py:790(_get_handles)
        1    0.000    0.000    0.000    0.000 subprocess.py:1028(_handle_exitstatus)
        1    0.000    0.000    0.000    0.000 codecs.py:302(__init__)
        1    0.000    0.000    0.000    0.000 {method 'decode' of 'str' objects}
        1    0.000    0.000    0.000    0.000 genericpath.py:34(isfile)
        1    0.000    0.000    0.000    0.000 {posix.waitpid}
        1    0.000    0.000    0.000    0.000 genericpath.py:23(exists)
        4    0.000    0.000    0.000    0.000 UserDict.py:103(__contains__)
        1    0.000    0.000    0.000    0.000 _cloud_sdk.py:72(get_application_default_credentials_path)
        2    0.000    0.000    0.000    0.000 _weakrefset.py:70(__contains__)
        4    0.000    0.000    0.000    0.000 {method 'startswith' of 'str' objects}
        1    0.000    0.000    0.000    0.000 credentials.py:52(__init__)
        1    0.000    0.000    0.000    0.000 {method 'close' of 'file' objects}
        1    0.000    0.000    0.000    0.000 credentials.py:192(__init__)
        3    0.000    0.000    0.000    0.000 {len}
        1    0.000    0.000    0.000    0.000 six.py:598(iterkeys)
```

**Comment by theacodes** [comment] 2018-08-24 19:40
Can't imagine why the file read would take a long time, but `default()` final check is looking for the Compute Engine metadata server, so it makes a network call if it can't find credentials before then.

Either way, I would definitely recommend caching the credentials and just passing them into your clients if you're creating a lot of them.

**Comment by max-sixty** [comment] 2018-08-24 20:03
I continued looking... The delay is driven by the default project by calling `gcloud config config-helper --format json` in a shell (which IIRC is a python application?). 

Everything else takes 1-2ms

https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/_cloud_sdk.py#L112

**Comment by theacodes** [comment] 2018-08-24 20:30
Unfortunately there's not much we can do to get around that. :/

**Comment by max-sixty** [comment] 2018-08-24 21:05
OK.

Am I correct in thinking that the gcloud library is in python? Can we do whatever that's doing to evaluate the command (or even import the function), rather than calling out via `subprocess`?
Similar to how we access the credentials file directly, rather than calling `gcloud` for those.

There's lots I don't understand about these libraries, so forgive me if these are obvious questions.

**Comment by theacodes** [comment] 2018-08-24 21:06
It is, but that's an implementation detail. We previously *did* try to do the same logic as gcloud, but it's also considered an implementation detail. What we do now is the "proper" thing to do in terms of interface contract - gcloud is allowed to change its internal config files at *any* time but must maintain compatibility for the `config-helper` command.

I'm going to close this for now, but happy to still answer any more questions/concerns.

**Closed by theacodes** 2018-08-24 21:06 UTC

**Comment by max-sixty** [comment] 2018-08-24 22:28
That logic certainly makes sense, thanks for your replies.

One more question: currently we subprocess the call _before_ checking the environment vars for an explicit definition:

https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/edfe24602051969e32917e82bcedd2bace43e260/google/auth/_default.py#L294

and then a couple of lines later, we throw that away if the env var is set:

https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/edfe24602051969e32917e82bcedd2bace43e260/google/auth/_default.py#L297

Would it be reasonable to only make the slow 500ms calls if we need to make them?

**Comment by max-sixty** [comment] 2018-08-27 17:54
@theacodes wanted to ensure you saw the last comment re the call running even when not needed, given it was after this closed and on a Friday afternoon!

Hope it's OK to ping you - I know you're running a big project already, and understood if you de-prioritize this and encourage applications to cache creds instead

**Comment by theacodes** [comment] 2018-08-27 18:08
The resolver [exits](https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/_default.py#L304) when it finds credentials, so explicit credentials should short-circuit that?

**Comment by theacodes** [comment] 2018-08-27 18:09
Oh I see what you're saying, this is specific to the *project id*. In that case, we still need to do the subprocess call if we're getting credentials from Cloud SDK. This is working as intended. If you wish to completely short-circuit this, use a service account with `GOOGLE_APPLICATION_CREDENTIALS`.

**Comment by max-sixty** [comment] 2018-08-27 18:25
>  In that case, we still need to do the subprocess call if we're getting credentials from Cloud SDK

We don't need to do the subprocess call to get credentials - those are pulled from the file directly (which takes < 1ms): https://github.com/GoogleCloudPlatform/google-auth-library-python/blob/master/google/auth/_default.py#L143

We only need to do the call to get the project id.

Though I understand that something like a param of `get_credentials_only=False` would add some complexity.
