### ISSUE TITLE
ERROR:root:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f2088dceb90>" raised exception!

### ISSUE THREAD

**Issue by gkayas** [GoogleCloudPlatform/google-auth-library-python#276] opened 2018-07-01 19:51 UTC
I am trying to use Google Cloud Speech. I have a good number of audio files (around 2K). I wrote a python script to get the transcripts of the audio files from Google Speech. For first few files, I got the transcripts smoothly but for later files, I receive an exception.  The exceptions occurred in an arbitrary manner, I have tested several times with my script to confirm that.  The traceback of the exception is like below:

```
ERROR:root:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f2088dceb90>" raised exception!
Traceback (most recent call last):
  File "/home/kayas/.local/lib/python2.7/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    callback_state, callback))
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/transport/requests.py", line 124, in __call__
    six.raise_from(new_exc, caught_exc)
  File "/home/kayas/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
TransportError: HTTPSConnectionPool(host='accounts.google.com', port=443): Max retries exceeded with url: /o/oauth2/token (Caused by SSLError(IOError(24, 'Too many open files'),))
/home/kayas/different_model_results/datasets/LibriSpeech/dev-clean/2277/149896/2277-149896-0025.flac HE ROSE FROM HIS CHAIR AND WENT AND LOOKED OUT INTO THE STREET
ERROR:root:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7f2088dcefd0>" raised exception!
Traceback (most recent call last):
  File "/home/kayas/.local/lib/python2.7/site-packages/grpc/_plugin_wrapping.py", line 77, in __call__
    callback_state, callback))
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 77, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
    headers)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/credentials.py", line 122, in before_request
    self.refresh(request)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/oauth2/service_account.py", line 322, in refresh
    request, self._token_uri, assertion)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
    response_data = _token_endpoint_request(request, token_uri, body)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/oauth2/_client.py", line 106, in _token_endpoint_request
    method='POST', url=token_uri, headers=headers, body=body)
  File "/home/kayas/.local/lib/python2.7/site-packages/google/auth/transport/requests.py", line 124, in __call__
    six.raise_from(new_exc, caught_exc)
  File "/home/kayas/.local/lib/python2.7/site-packages/six.py", line 737, in raise_from
    raise value
```

**Comment by louking** [comment] 2018-07-01 20:20
I'm not an expert in the auth library, but I had an arbitrary error in
another system, and it was environmental.

I would think "Caused by SSLError(IOError(24, 'Too many open files')" would
be a clue as to what is going on here.

Possibly a logic error in how you're closing files after you're done with
them?

**Closed** 2018-07-01 22:19 UTC

**Comment by BurakaKrishna** [comment] 2020-08-11 16:44
Hello @gkayas i had same issue when trying to run few files for transcription, were you able to solve it ?

**Comment by nguaman** [comment] 2022-06-15 21:43
I had a similar issue but with pubsub

Sometimes works and others doesn't.  
I use python3.9 and the lasted version of pub sub.

```
AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x7faf7d84a580>" raised exception!
Traceback (most recent call last):
  File "/home/nguaman/.local/lib/python3.9/site-packages/grpc/_plugin_wrapping.py", line 89, in __call__
    self._metadata_plugin(
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 101, in __call__
    callback(self._get_authorization_headers(context), None)
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/transport/grpc.py", line 87, in _get_authorization_headers
    self._credentials.before_request(
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/credentials.py", line 134, in before_request
    self.apply(headers)
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/credentials.py", line 110, in apply
    _helpers.from_bytes(token or self.token)
  File "/home/nguaman/.local/lib/python3.9/site-packages/google/auth/_helpers.py", line 126, in from_bytes
    raise ValueError("{0!r} could not be converted to unicode".format(value))
ValueError: None could not be converted to unicode
```
